### COMPRAS

GET http://localhost:3333/compras

### COMPRAS

POST http://localhost:3333/compras
Content-Type: application/json

{
    "price": "90",
    "name": "Picanha",
    "description": "Faz o L"
}